name: npm-publish
on:
  push:
    branches:
      - master # Change this to your default branch
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 10.0.0
    - run: npm install
    - run: npm test
    - run: |
        npm login --registry=https://npm.pkg.github.com
        tbm0115
        ${{ secrets.GITHUB_TOKEN }}
        tbm0115@gmail.com
    - run: npm publish

